apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-data
  namespace: bookstack
spec:
  selector:
    matchLabels:
      app: bookstack
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
