apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-local-pv
  labels:
    app: bookstack
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/bookstack
