apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/bookstack_config   # فولدر منفصل تماماً
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config-pvc
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/bookstack_storage  # فولدر منفصل تماماً
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-storage-pvc
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
