apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: bookstack-data
  namespace: bookstack
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: local
      app: bookstack