apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: bookstack
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  selector:
   matchLabels:
     type: local
     app: mariadb 
