apiVesion: v1
kind: Deployment
metadata:
  name: mariadb
  namespace: bookstack
  labels:
    app: mariadb
spec:
  replicaas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: linuxserver/mariadb:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_USERNAME
        - namme: MYSQL_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_PASSWORD

