apiVersion: v1
kind: secret
metadata:
  name: bookstack-secrets
  namespace: bookstack
type: Opaque
stringData:
  DB_HOST: mariadb-service.default.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: "bookstack"
  DB_USERNAME: "bookstack"
  DB_PASSWORD: "Mariadb@Pass"
  APP_URL: "http://localhost:80"
