apiVersion: v1
kind: secret
metadata:
  name: bookstack-secrets
  namespace: bookstack
type: Opaque
stringData:
  DB_HOST: 10.244.0.5
  DB_PORT: "3306"
  DB_DATABASE: "bookstack"
  DB_USERNAME: "bookstack"
  DB_PASSWORD: "Mariadb@Pass"
  APP_URL: "http://localhost:8080"
  APP_KEY: "YmFzZTY0OjBUUlJMekJwOFJWNWVveGp5RTlmeXRnTG82TGZ1MHkrUEFRMm1jZlBtQ009"
