apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secrets
  namespace: bookstack
type: Opaque
stringData:
  DB_HOST: "mariadb-service"
  DB_PORT: "3306"
  DB_DATABASE: "bookstack"
  DB_USERNAME: "bookstack"
  DB_PASSWORD: "Mariadb@Pass"
  APP_URL: "http://bookstack.local"
  APP_KEY: "base64:kKClRI/FXMRxJ8OCDuNfprpXQYpS4KE0QHlTLDnaiKw="
